# Generated by Django 3.1.3 on 2020-11-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
