# Generated by Django 3.1.3 on 2020-11-29 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20201128_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='dosis',
            field=models.CharField(default='2 veces al dia', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='medicamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.medicamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='observaciones',
            field=models.TextField(default='Bailo, Bailo, y se pone a tronar'),
            preserve_default=False,
        ),
    ]
