# Generated by Django 3.1.3 on 2020-11-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20201128_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
