# Generated by Django 3.1.3 on 2020-11-30 16:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_geolocalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='geoubicacion',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
