# Generated by Django 3.1.3 on 2020-11-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_remove_paciente_geolocalizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='geoubicacion',
            new_name='geolocalizacion',
        ),
    ]
